/* The following code was generated by JFlex 1.7.0 */

package fnplot.syntax;

/* Specification for ArithExp tokens */

// user customisations
import java_cup.runtime.*;

// Jlex directives

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>syntax/FnPlotLexer</tt>
 */
public class FnPlotLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\3\1\1\1\46\1\47\1\1\22\0\1\72\1\62"+
    "\1\65\1\10\1\0\1\24\1\0\1\0\1\26\1\27\1\22\1\21"+
    "\1\31\1\6\1\7\1\23\2\12\10\5\1\14\1\37\1\61\1\25"+
    "\1\60\1\13\1\73\6\71\6\67\1\63\15\67\1\15\1\66\1\17"+
    "\1\16\1\4\1\0\1\42\1\11\1\50\1\40\1\33\1\41\1\64"+
    "\1\52\1\35\2\67\1\32\1\67\1\36\1\43\1\45\1\56\1\44"+
    "\1\51\1\34\1\55\1\57\1\67\1\70\1\54\1\53\1\30\1\0"+
    "\1\20\7\0\1\46\32\0\1\66\u15df\0\1\66\u097f\0\13\66\35\0"+
    "\1\46\1\46\5\0\1\66\57\0\1\66\u0fa0\0\1\66\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\5\3\1\25"+
    "\7\3\1\26\1\27\1\0\1\3\1\0\1\2\1\0"+
    "\1\30\1\4\1\0\1\31\1\32\1\33\2\0\1\34"+
    "\1\35\6\3\1\36\1\37\3\3\1\40\7\3\1\41"+
    "\1\42\1\43\1\3\2\0\1\44\1\45\1\0\1\46"+
    "\7\3\1\47\1\3\1\50\1\51\3\3\1\52\1\3"+
    "\1\53\5\3\1\54\1\55\1\34\1\56\1\57\1\60"+
    "\1\3\1\61\1\62\2\3\1\63\1\3\1\64\1\65"+
    "\1\66\1\67\6\3\1\70\1\71\3\3\1\72\1\73"+
    "\2\3\1\74\1\3\1\75\1\3\1\76\1\77\1\3"+
    "\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\74\0\170\0\264\0\360\0\74\0\u012c"+
    "\0\74\0\74\0\74\0\74\0\74\0\74\0\74\0\u0168"+
    "\0\74\0\u01a4\0\74\0\74\0\74\0\74\0\u01e0\0\u021c"+
    "\0\u0258\0\u0294\0\u02d0\0\74\0\u030c\0\u0348\0\u0384\0\u03c0"+
    "\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564\0\u05a0"+
    "\0\u05dc\0\360\0\u0618\0\u0654\0\u0690\0\74\0\74\0\74"+
    "\0\u06cc\0\u0708\0\u0744\0\74\0\u0780\0\u07bc\0\u07f8\0\u0834"+
    "\0\u0870\0\u08ac\0\u08e8\0\170\0\u0924\0\u0960\0\u099c\0\170"+
    "\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\74"+
    "\0\74\0\74\0\u0b7c\0\u0bb8\0\u0bf4\0\u0690\0\u06cc\0\u0c30"+
    "\0\170\0\u0c6c\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4"+
    "\0\170\0\u0e10\0\170\0\170\0\u0e4c\0\u0e88\0\u0ec4\0\170"+
    "\0\u0f00\0\170\0\u0f3c\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\74"+
    "\0\74\0\u0708\0\170\0\170\0\170\0\u1068\0\74\0\170"+
    "\0\u10a4\0\u10e0\0\u111c\0\u1158\0\170\0\170\0\170\0\170"+
    "\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0\0\74\0\u12fc"+
    "\0\u1338\0\u1374\0\u13b0\0\74\0\170\0\u13ec\0\u1428\0\170"+
    "\0\u1464\0\170\0\u14a0\0\170\0\170\0\u14dc\0\170";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\2\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\4\1\5\1\0\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\4\1\36\1\37\1\4\1\40\1\0\1\3\1\41"+
    "\1\42\1\43\5\4\1\44\1\45\1\46\1\4\1\47"+
    "\1\50\1\0\3\4\1\51\101\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\7\0\1\5\1\52\1\53\2\0\1\5"+
    "\66\0\1\54\4\0\1\54\72\0\1\55\21\0\1\56"+
    "\1\57\4\0\1\60\26\0\1\61\25\0\1\62\1\63"+
    "\75\0\1\64\52\0\2\4\3\0\2\4\17\0\1\4"+
    "\1\65\1\4\1\66\1\4\1\0\2\4\1\67\3\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\1\70\4\4\1\0\6\4\2\0"+
    "\6\4\1\71\1\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\5\4\1\0\6\4\2\0"+
    "\2\4\1\72\5\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\4\4\1\73\1\0\1\4"+
    "\1\74\4\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\5\4\1\0\3\4"+
    "\1\75\2\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\1\4\1\76\3\4"+
    "\1\0\6\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\4\4\1\77\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\5\4\1\0\4\4\1\100"+
    "\1\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\5\4\1\0\2\4\1\101"+
    "\1\4\1\102\1\4\2\0\10\4\3\0\2\4\2\0"+
    "\3\4\6\0\2\4\3\0\2\4\17\0\5\4\1\0"+
    "\1\103\1\4\1\104\3\4\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\3\4"+
    "\1\105\1\4\1\0\6\4\2\0\5\4\1\106\2\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\1\4\1\107\3\4\1\0\6\4\2\0\10\4"+
    "\3\0\2\4\2\0\3\4\27\0\1\110\73\0\1\111"+
    "\73\0\1\112\52\0\2\4\3\0\2\4\17\0\1\4"+
    "\1\113\3\4\1\0\6\4\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\3\0\1\114\1\0\1\114\1\0\1\114"+
    "\3\0\2\114\17\0\5\114\1\0\20\114\3\0\2\114"+
    "\1\0\5\114\74\0\1\115\5\0\1\53\4\0\1\53"+
    "\66\0\1\54\1\52\3\0\1\54\73\0\1\116\66\0"+
    "\1\117\3\0\2\117\20\0\1\117\4\0\3\117\5\0"+
    "\1\117\20\0\1\117\2\0\22\62\1\120\51\62\1\63"+
    "\1\0\44\63\2\0\24\63\4\0\2\4\3\0\2\4"+
    "\17\0\2\4\1\121\2\4\1\0\6\4\2\0\10\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\1\4\1\122\6\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\3\4\1\123\4\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\1\4\1\124\6\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\5\4\1\125\1\4"+
    "\1\126\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\1\4\1\127\3\4\1\0\6\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\5\4\1\0\6\4\2\0\1\4\1\130"+
    "\6\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\2\4\1\131\2\4\1\0\6\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\1\132\4\4\1\0\1\4\1\133\4\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\5\4\1\0\1\134\5\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\3\4\1\135\1\4\1\0\6\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\3\4\1\136\1\4\1\0\3\4\1\137"+
    "\2\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\5\4\1\0\4\4\1\140"+
    "\1\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\1\141\4\4\1\0\4\4"+
    "\1\142\1\4\2\0\1\4\1\143\6\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\5\4"+
    "\1\0\6\4\2\0\3\4\1\144\4\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\1\145\1\4\17\0"+
    "\5\4\1\0\6\4\2\0\10\4\3\0\2\4\2\0"+
    "\3\4\6\0\2\4\3\0\2\4\17\0\5\4\1\0"+
    "\2\4\1\146\3\4\2\0\10\4\3\0\2\4\2\0"+
    "\3\4\6\0\2\4\3\0\2\4\17\0\2\4\1\147"+
    "\2\4\1\0\6\4\2\0\10\4\3\0\2\4\2\0"+
    "\3\4\3\0\1\114\1\0\1\114\1\0\1\114\3\0"+
    "\2\114\17\0\5\114\1\0\20\114\3\0\2\114\1\150"+
    "\5\114\73\0\1\151\1\0\22\62\1\120\1\152\50\62"+
    "\4\0\2\4\3\0\2\4\17\0\2\4\1\153\2\4"+
    "\1\0\6\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\5\4\1\0\6\4"+
    "\2\0\4\4\1\154\3\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\1\4\1\155\3\4"+
    "\1\0\6\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\5\4\1\0\2\4"+
    "\1\156\3\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\1\157\16\0\5\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\4\4\1\160\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\1\4\1\161\3\4\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\1\4\1\162\3\4\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\5\4\1\0\4\4\1\163\1\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\4\4\1\164\1\0\6\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\5\4\1\0\6\4\2\0\1\165\7\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\1\166\4\4\1\0\6\4\2\0\10\4\3\0"+
    "\2\4\2\0\3\4\6\0\2\4\3\0\2\4\17\0"+
    "\1\4\1\167\3\4\1\0\6\4\2\0\10\4\3\0"+
    "\2\4\2\0\3\4\6\0\2\4\3\0\2\4\17\0"+
    "\1\4\1\170\3\4\1\0\6\4\2\0\10\4\3\0"+
    "\2\4\2\0\3\4\6\0\2\4\3\0\2\4\17\0"+
    "\5\4\1\0\6\4\2\0\1\4\1\171\6\4\3\0"+
    "\2\4\2\0\3\4\6\0\2\4\3\0\2\4\17\0"+
    "\5\4\1\0\5\4\1\172\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\5\4"+
    "\1\0\6\4\2\0\10\4\3\0\1\173\1\4\2\0"+
    "\3\4\6\0\2\4\3\0\2\4\17\0\1\174\4\4"+
    "\1\0\6\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\5\4\1\0\4\4"+
    "\1\175\1\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\17\0\2\4\1\176\2\4"+
    "\1\0\6\4\2\0\10\4\3\0\2\4\2\0\3\4"+
    "\6\0\2\4\3\0\2\4\1\177\16\0\5\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\2\4\1\200\2\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\2\4\1\201\2\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\3\4\1\202\1\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\17\0\3\4\1\203\1\4\1\0"+
    "\6\4\2\0\10\4\3\0\2\4\2\0\3\4\6\0"+
    "\2\4\3\0\2\4\1\204\16\0\5\4\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\2\4\1\205\2\4\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\1\4\1\206\3\4\1\0\6\4"+
    "\2\0\10\4\3\0\2\4\2\0\3\4\6\0\2\4"+
    "\3\0\2\4\17\0\1\207\4\4\1\0\6\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\5\4\1\0\4\4\1\210\1\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\5\4\1\0\1\4\1\211\4\4\2\0"+
    "\10\4\3\0\2\4\2\0\3\4\6\0\2\4\3\0"+
    "\2\4\17\0\4\4\1\212\1\0\6\4\2\0\10\4"+
    "\3\0\2\4\2\0\3\4\6\0\2\4\3\0\2\4"+
    "\17\0\5\4\1\0\6\4\2\0\10\4\3\0\1\213"+
    "\1\4\2\0\3\4\6\0\2\4\3\0\2\4\17\0"+
    "\4\4\1\214\1\0\6\4\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\5\4"+
    "\1\0\6\4\2\0\4\4\1\215\3\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\3\4"+
    "\1\216\1\4\1\0\6\4\2\0\10\4\3\0\2\4"+
    "\2\0\3\4\6\0\2\4\3\0\2\4\17\0\4\4"+
    "\1\217\1\0\6\4\2\0\10\4\3\0\2\4\2\0"+
    "\3\4\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\1\0\7\11\1\1\1\11"+
    "\1\1\4\11\5\1\1\11\11\1\1\0\1\1\1\0"+
    "\1\1\1\0\2\1\1\0\3\11\2\0\1\1\1\11"+
    "\23\1\3\11\1\1\2\0\2\1\1\0\27\1\2\11"+
    "\5\1\1\11\17\1\1\11\4\1\1\11\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public int getChar() {
	return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	return yyline + 1;
    }

    public String getText() {
	return yytext();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FnPlotLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [68] { //skip newline, but reset char counter"+ZZ_NL+"\t\t\tyycolumn = 0; }");
            { //skip newline, but reset char counter
			yycolumn = 0;
            } 
            // fall through
          case 65: break;
          case 2: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [72] { //skip whitespace }");
            { //skip whitespace
            } 
            // fall through
          case 66: break;
          case 3: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [183] { // VARIABLE"+ZZ_NL+"\t       return new Symbol(sym.VARIABLE, yytext()); }");
            { // VARIABLE
	       return new Symbol(sym.VARIABLE, yytext());
            } 
            // fall through
          case 67: break;
          case 4: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [164] { // INTEGER"+ZZ_NL+"\t       return new Symbol(sym.INTEGER, "+ZZ_NL+"\t\t\t\t new Integer(yytext())); }");
            { // INTEGER
	       return new Symbol(sym.INTEGER, 
				 new Integer(yytext()));
            } 
            // fall through
          case 68: break;
          case 5: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [76] { return new Symbol(sym.MINUS); }");
            { return new Symbol(sym.MINUS);
            } 
            // fall through
          case 69: break;
          case 6: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [89] { return new Symbol(sym.DOT); }");
            { return new Symbol(sym.DOT);
            } 
            // fall through
          case 70: break;
          case 7: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [100] { return new Symbol(sym.COLON); }");
            { return new Symbol(sym.COLON);
            } 
            // fall through
          case 71: break;
          case 8: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { return new Symbol(sym.RSQBRACKET); }");
            { return new Symbol(sym.RSQBRACKET);
            } 
            // fall through
          case 72: break;
          case 9: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [135] { return new Symbol(sym.EXPO); }");
            { return new Symbol(sym.EXPO);
            } 
            // fall through
          case 73: break;
          case 10: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [102] { return new Symbol(sym.LSQBRACKET); }");
            { return new Symbol(sym.LSQBRACKET);
            } 
            // fall through
          case 74: break;
          case 11: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [86] { return new Symbol(sym.RBRACE); }");
            { return new Symbol(sym.RBRACE);
            } 
            // fall through
          case 75: break;
          case 12: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [75] { return new Symbol(sym.PLUS); }");
            { return new Symbol(sym.PLUS);
            } 
            // fall through
          case 76: break;
          case 13: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [77] { return new Symbol(sym.MUL); }");
            { return new Symbol(sym.MUL);
            } 
            // fall through
          case 77: break;
          case 14: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [78] { return new Symbol(sym.DIV); }");
            { return new Symbol(sym.DIV);
            } 
            // fall through
          case 78: break;
          case 15: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [79] { return new Symbol(sym.MOD); }");
            { return new Symbol(sym.MOD);
            } 
            // fall through
          case 79: break;
          case 16: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [80] { return new Symbol(sym.ASSIGN); }");
            { return new Symbol(sym.ASSIGN);
            } 
            // fall through
          case 80: break;
          case 17: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [82] { return new Symbol(sym.LPAREN); }");
            { return new Symbol(sym.LPAREN);
            } 
            // fall through
          case 81: break;
          case 18: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [83] { return new Symbol(sym.RPAREN); }");
            { return new Symbol(sym.RPAREN);
            } 
            // fall through
          case 82: break;
          case 19: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [85] { return new Symbol(sym.LBRACE); }");
            { return new Symbol(sym.LBRACE);
            } 
            // fall through
          case 83: break;
          case 20: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [88] { return new Symbol(sym.COMMA); }");
            { return new Symbol(sym.COMMA);
            } 
            // fall through
          case 84: break;
          case 21: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [94] { return new Symbol(sym.SEMI); }");
            { return new Symbol(sym.SEMI);
            } 
            // fall through
          case 85: break;
          case 22: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [139] { return new Symbol(sym.GREATER); }");
            { return new Symbol(sym.GREATER);
            } 
            // fall through
          case 86: break;
          case 23: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [140] { return new Symbol(sym.LESSER); }");
            { return new Symbol(sym.LESSER);
            } 
            // fall through
          case 87: break;
          case 24: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [177] { // DOUBLE"+ZZ_NL+"\t       return new Symbol(sym.DOUBLE, "+ZZ_NL+"\t\t\t\t new Double(yytext())); }");
            { // DOUBLE
	       return new Symbol(sym.DOUBLE, 
				 new Double(yytext()));
            } 
            // fall through
          case 88: break;
          case 25: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [153] { return new Symbol(sym.NIL); }");
            { return new Symbol(sym.NIL);
            } 
            // fall through
          case 89: break;
          case 26: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [137] { return new Symbol(sym.BOOL_TRUE); }");
            { return new Symbol(sym.BOOL_TRUE);
            } 
            // fall through
          case 90: break;
          case 27: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [151] { return new Symbol(sym.BOOL_FALSE); }");
            { return new Symbol(sym.BOOL_FALSE);
            } 
            // fall through
          case 91: break;
          case 28: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [113] {  }");
            { 
            } 
            // fall through
          case 92: break;
          case 29: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [144] { return new Symbol(sym.EEQUAL); }");
            { return new Symbol(sym.EEQUAL);
            } 
            // fall through
          case 93: break;
          case 30: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [92] { return new Symbol(sym.IN); }");
            { return new Symbol(sym.IN);
            } 
            // fall through
          case 94: break;
          case 31: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [120] { return new Symbol(sym.IF); }");
            { return new Symbol(sym.IF);
            } 
            // fall through
          case 95: break;
          case 32: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [107] { return new Symbol(sym.OR); }");
            { return new Symbol(sym.OR);
            } 
            // fall through
          case 96: break;
          case 33: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [141] { return new Symbol(sym.GREATEREQUAL); }");
            { return new Symbol(sym.GREATEREQUAL);
            } 
            // fall through
          case 97: break;
          case 34: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [142] { return new Symbol(sym.LESSEREQUAL); }");
            { return new Symbol(sym.LESSEREQUAL);
            } 
            // fall through
          case 98: break;
          case 35: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [143] { return new Symbol(sym.NOTEQUAL); }");
            { return new Symbol(sym.NOTEQUAL);
            } 
            // fall through
          case 99: break;
          case 36: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [157] { return new Symbol(sym.BIN_INTEGER,yytext().substring(2) ); }");
            { return new Symbol(sym.BIN_INTEGER,yytext().substring(2) );
            } 
            // fall through
          case 100: break;
          case 37: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [159] { return new Symbol( sym.HEX_INTEGER,yytext().substring(2) ); }");
            { return new Symbol( sym.HEX_INTEGER,yytext().substring(2) );
            } 
            // fall through
          case 101: break;
          case 38: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [91] { return new Symbol(sym.LET); }");
            { return new Symbol(sym.LET);
            } 
            // fall through
          case 102: break;
          case 39: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [108] { return new Symbol(sym.NOT); }");
            { return new Symbol(sym.NOT);
            } 
            // fall through
          case 103: break;
          case 40: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [98] { return new Symbol(sym.DEF); }");
            { return new Symbol(sym.DEF);
            } 
            // fall through
          case 104: break;
          case 41: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [106] { return new Symbol(sym.AND); }");
            { return new Symbol(sym.AND);
            } 
            // fall through
          case 105: break;
          case 42: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [133] { return new Symbol(sym.CDR); }");
            { return new Symbol(sym.CDR);
            } 
            // fall through
          case 106: break;
          case 43: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [132] { return new Symbol(sym.CAR); }");
            { return new Symbol(sym.CAR);
            } 
            // fall through
          case 107: break;
          case 44: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [155] { return new Symbol(sym.STR,yytext()); }");
            { return new Symbol(sym.STR,yytext());
            } 
            // fall through
          case 108: break;
          case 45: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [161] { return new Symbol (sym.CONCAT); }");
            { return new Symbol (sym.CONCAT);
            } 
            // fall through
          case 109: break;
          case 46: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [129] { return new Symbol(sym.LIST); }");
            { return new Symbol(sym.LIST);
            } 
            // fall through
          case 110: break;
          case 47: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [124] { return new Symbol(sym.MODIFIER,yytext()); }");
            { return new Symbol(sym.MODIFIER,yytext());
            } 
            // fall through
          case 111: break;
          case 48: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [118] { return new Symbol(sym.ELSE); }");
            { return new Symbol(sym.ELSE);
            } 
            // fall through
          case 112: break;
          case 49: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [127] { return new Symbol(sym.IS_EQV); }");
            { return new Symbol(sym.IS_EQV);
            } 
            // fall through
          case 113: break;
          case 50: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [119] { return new Symbol(sym.THEN); }");
            { return new Symbol(sym.THEN);
            } 
            // fall through
          case 114: break;
          case 51: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [131] { return new Symbol(sym.PAIR); }");
            { return new Symbol(sym.PAIR);
            } 
            // fall through
          case 115: break;
          case 52: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [123] { return new Symbol(sym.PROC); }");
            { return new Symbol(sym.PROC);
            } 
            // fall through
          case 116: break;
          case 53: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [122] { return new Symbol(sym.CALL); }");
            { return new Symbol(sym.CALL);
            } 
            // fall through
          case 117: break;
          case 54: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [117] { return new Symbol(sym.CASE); }");
            { return new Symbol(sym.CASE);
            } 
            // fall through
          case 118: break;
          case 55: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [121] { return new Symbol(sym.SIZE); }");
            { return new Symbol(sym.SIZE);
            } 
            // fall through
          case 119: break;
          case 56: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [130] { return new Symbol(sym.IS_PAIR); }");
            { return new Symbol(sym.IS_PAIR);
            } 
            // fall through
          case 120: break;
          case 57: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [110] { return new Symbol(sym.PRINT); }");
            { return new Symbol(sym.PRINT);
            } 
            // fall through
          case 121: break;
          case 58: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [126] { return new Symbol(sym.IS_EQUAL); }");
            { return new Symbol(sym.IS_EQUAL);
            } 
            // fall through
          case 122: break;
          case 59: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [147] { return new Symbol(sym.HEAPINSERT); }");
            { return new Symbol(sym.HEAPINSERT);
            } 
            // fall through
          case 123: break;
          case 60: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [125] { return new Symbol(sym.SUBSTR); }");
            { return new Symbol(sym.SUBSTR);
            } 
            // fall through
          case 124: break;
          case 61: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [149] { return new Symbol(sym.GETMIN); }");
            { return new Symbol(sym.GETMIN);
            } 
            // fall through
          case 125: break;
          case 62: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [111] { return new Symbol(sym.PRINTLN); }");
            { return new Symbol(sym.PRINTLN);
            } 
            // fall through
          case 126: break;
          case 63: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [146] { return new Symbol(sym.HEAP); }");
            { return new Symbol(sym.HEAP);
            } 
            // fall through
          case 127: break;
          case 64: 
            System.out.println("line: "+(yyline+1)+" "+"char: "+yychar+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [148] { return new Symbol(sym.HEAPDELETE); }");
            { return new Symbol(sym.HEAPDELETE);
            } 
            // fall through
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java FnPlotLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        FnPlotLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new FnPlotLexer(reader);
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
