
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 12;
  public static final int PLUS = 8;
  public static final int RBRACE = 17;
  public static final int RPAREN = 3;
  public static final int SEMI = 19;
  public static final int IN = 15;
  public static final int BOOL_TRUE = 29;
  public static final int BOOL_FALSE = 30;
  public static final int CONCAT = 4;
  public static final int VARIABLE = 27;
  public static final int LPAREN = 2;
  public static final int RSQBRACKET = 5;
  public static final int COLON = 7;
  public static final int LBRACE = 16;
  public static final int LSQBRACKET = 6;
  public static final int CAR = 24;
  public static final int HEX_INTEGER = 22;
  public static final int EXPO = 20;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int BIN_INTEGER = 21;
  public static final int LET = 14;
  public static final int STR = 28;
  public static final int ASSIGN = 13;
  public static final int INTEGER = 25;
  public static final int MUL = 10;
  public static final int PAIR = 23;
  public static final int DOUBLE = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "CONCAT",
  "RSQBRACKET",
  "LSQBRACKET",
  "COLON",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "LET",
  "IN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "EXPO",
  "BIN_INTEGER",
  "HEX_INTEGER",
  "PAIR",
  "CAR",
  "INTEGER",
  "DOUBLE",
  "VARIABLE",
  "STR",
  "BOOL_TRUE",
  "BOOL_FALSE"
  };
}

