
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EEQUAL = 25;
  public static final int CONCAT = 4;
  public static final int STR = 60;
  public static final int CASE = 47;
  public static final int CAR = 28;
  public static final int DOUBLE = 58;
  public static final int INTEGER = 57;
  public static final int NOTEQUAL = 24;
  public static final int CDR = 29;
  public static final int LPAREN = 2;
  public static final int GREATER = 20;
  public static final int SEMI = 19;
  public static final int EXPO = 26;
  public static final int PRINTLN = 48;
  public static final int MODIFIER = 65;
  public static final int BOOL_TRUE = 61;
  public static final int MINUS = 9;
  public static final int RPAREN = 3;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int NIL = 32;
  public static final int OR = 51;
  public static final int IN = 15;
  public static final int COMMA = 18;
  public static final int CALL = 42;
  public static final int LESSEREQUAL = 23;
  public static final int BNOT = 56;
  public static final int BAND = 54;
  public static final int DIV = 11;
  public static final int HEAPINSERT = 37;
  public static final int LESSER = 21;
  public static final int PLUS = 8;
  public static final int IF = 44;
  public static final int ASSIGN = 13;
  public static final int IS_EQUAL = 34;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int HEAP = 36;
  public static final int SIZE = 43;
  public static final int error = 1;
  public static final int MUL = 10;
  public static final int MOD = 12;
  public static final int LSQBRACKET = 6;
  public static final int PAIR = 27;
  public static final int IS_EQV = 33;
  public static final int IS_PAIR = 30;
  public static final int GETMIN = 39;
  public static final int GREATEREQUAL = 22;
  public static final int BOOL_FALSE = 62;
  public static final int COLON = 7;
  public static final int BOR = 55;
  public static final int ELSE = 46;
  public static final int LBRACE = 16;
  public static final int VARIABLE = 59;
  public static final int LIST = 31;
  public static final int SUBSTR = 35;
  public static final int LET = 14;
  public static final int BIN_INTEGER = 63;
  public static final int THEN = 45;
  public static final int RBRACE = 17;
  public static final int RSQBRACKET = 5;
  public static final int HEX_INTEGER = 64;
  public static final int PROC = 40;
  public static final int DEF = 53;
  public static final int HEAPDELETE = 38;
  public static final int PRINT = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "CONCAT",
  "RSQBRACKET",
  "LSQBRACKET",
  "COLON",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "LET",
  "IN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "GREATER",
  "LESSER",
  "GREATEREQUAL",
  "LESSEREQUAL",
  "NOTEQUAL",
  "EEQUAL",
  "EXPO",
  "PAIR",
  "CAR",
  "CDR",
  "IS_PAIR",
  "LIST",
  "NIL",
  "IS_EQV",
  "IS_EQUAL",
  "SUBSTR",
  "HEAP",
  "HEAPINSERT",
  "HEAPDELETE",
  "GETMIN",
  "PROC",
  "DOT",
  "CALL",
  "SIZE",
  "IF",
  "THEN",
  "ELSE",
  "CASE",
  "PRINTLN",
  "PRINT",
  "AND",
  "OR",
  "NOT",
  "DEF",
  "BAND",
  "BOR",
  "BNOT",
  "INTEGER",
  "DOUBLE",
  "VARIABLE",
  "STR",
  "BOOL_TRUE",
  "BOOL_FALSE",
  "BIN_INTEGER",
  "HEX_INTEGER",
  "MODIFIER"
  };
}

